# Generated by Django 3.0.10 on 2021-09-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssqlFrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_NAME', models.CharField(max_length=500)),
                ('_NUMERICID', models.IntegerField()),
                ('_VALUE', models.CharField(max_length=500)),
                ('_TIMESTAMP', models.DateTimeField()),
                ('_QUALITY', models.IntegerField()),
            ],
        ),
    ]
