# Generated by Django 3.0.10 on 2021-09-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mssqlFrontEnd', '0002_temperatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperatures',
            old_name='_NAME',
            new_name='TemperatureName',
        ),
        migrations.RenameField(
            model_name='temperatures',
            old_name='_NUMERICID',
            new_name='TemperatureNumericID',
        ),
        migrations.RenameField(
            model_name='temperatures',
            old_name='_QUALITY',
            new_name='TemperatureQuality',
        ),
        migrations.RenameField(
            model_name='temperatures',
            old_name='_TIMESTAMP',
            new_name='TemperatureTimeStamp',
        ),
        migrations.RenameField(
            model_name='temperatures',
            old_name='_VALUE',
            new_name='TemperatureValue',
        ),
    ]
