# Generated by Django 3.0.10 on 2021-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssqlFrontEnd', '0003_auto_20210927_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PressureName', models.CharField(max_length=500)),
                ('PressureNumericID', models.IntegerField()),
                ('PressureValue', models.CharField(max_length=500)),
                ('PressureTimeStamp', models.DateTimeField()),
                ('PressureQuality', models.IntegerField()),
            ],
        ),
    ]
