# Generated by Django 3.0.10 on 2021-10-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssqlFrontEnd', '0004_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatures',
            name='TemperatureValue',
            field=models.IntegerField(),
        ),
    ]
